# Generated by Django 3.2.12 on 2022-03-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
