# Generated by Django 3.2.12 on 2022-03-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_auto_20220324_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_category', models.CharField(max_length=50)),
                ('quantity_sold', models.IntegerField()),
                ('seller_id', models.IntegerField()),
            ],
        ),
    ]
