# Generated by Django 3.2.12 on 2022-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='message',
            name='client_name',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
